name: Farms
version: "1.0.0"
main: com.github.triikow.farms.plugin.FarmsPlugin
api-version: "1.21"

depend: [WorldEdit]

permissions:
  farms.farm:
    description: Allows using /farm
    default: true

  farms.admin:
    description: Allows using /farm admin
    default: op
  farms.admin.reload:
    description: Allows /farm admin reload
    default: op
  farms.admin.status:
    description: Allows /farm admin status
    default: op
  farms.admin.tp:
    description: Allows /farm admin tp
    default: op

  farms.preset.*:
    description: Allows selecting any island preset
    default: op
